spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:h2:mem:adm_videos;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: "org.h2.Driver"
  h2:
    console:
      enabled: true
      path: /h2
